cache: bundler

language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - jruby-9.1.6.0
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
